-- V11__create_order_item_table.sql
CREATE TABLE order_item (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id   BIGINT NOT NULL,
  product_id BIGINT NOT NULL,
  unit_price BIGINT   NOT NULL,
  quantity   BIGINT    NOT NULL,
  sub_total  BIGINT    NOT NULL,

  CONSTRAINT fk_orderitem_order
    FOREIGN KEY (order_id)   REFERENCES orders(id),

  CONSTRAINT fk_orderitem_product
    FOREIGN KEY (product_id) REFERENCES item(id)
);

CREATE INDEX idx_orderitem_order ON order_item(order_id);
