-- V9__create_cart_item_table.sql
CREATE TABLE cart_item (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cart_id BIGINT NOT NULL,
  product_id BIGINT NOT NULL,
  quantity INT NOT NULL,
  CONSTRAINT fk_cartitem_cart    FOREIGN KEY (cart_id)    REFERENCES cart(id),
  CONSTRAINT fk_cartitem_product FOREIGN KEY (product_id) REFERENCES item(id),
  CONSTRAINT uk_cart_product UNIQUE (cart_id, product_id)
);
